version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
      - image: circleci/node:10.0.0
    steps:
      - checkout
      - setup_remote_docker

      - run: docker build -t platzi .

      # run tests!
      - run: docker run platzi npm test

  deploy-qa:
    docker:
      - image: docker:17.05.0-ce-git
      - image: circleci/node:10.0.0
    steps:
      - checkout
      - run:
          command: npm install -g now
      - run:
          command: echo 'Deploying...'
      - run:
          command: URL=$(now --docker -t $NOW_TOKEN)
      - run:
          command: echo 'running acceptance on $URL'
      - run:
          command: curl --silent -L $URL

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-qa:
          requires:
            - build
