version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.0.0
    steps:
      - checkout
      - setup_remote_docker

      - run: docker build -t platzi .
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: docker run platzi npm test

  deploy-qa:
    docker:
      - image: circleci/node:10.0.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: Docker Deployment
          command: sh deployments/qa.sh 
  deploy-prod:
    docker:
      - image: circleci/node:10.0.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: Docker Deployment
          command: sh deployments/prod.sh 


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master
