version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
      - image: circleci/node:8.1.0
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: docker build -t platzi .
      - run: docker run platzi npm test
      - run: sh deployments/qa.sh 

  deploy-qa:
    docker:
      - image: docker:17.05.0-ce-git
      - image: circleci/node:10.0.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
        name: Docker Deployment
        command: sh deployments/qa.sh 
